runtime: python39
env: standard
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  ENCRYPTION_KEY: ""  # Set in GCP Console
  NTLM_SERVICE_URL: ""  # Set in GCP Console

entrypoint: gunicorn -b :$PORT main:app 