steps:
  # Get service account key from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$SERVICE_ACCOUNT_KEY" > /workspace/service-account-key.json
        echo "Activating service account..."
        gcloud auth activate-service-account --key-file=/workspace/service-account-key.json
    secretEnv: ['SERVICE_ACCOUNT_KEY']

  # Run setup.sh
  - name: 'bash'
    entrypoint: 'bash'
    args: ['scripts/setup.sh']
    env:
      - 'CLOUD_BUILD=1'
      - 'PYTHONPATH=/workspace'
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/service-account-key.json'

timeout: '1800s'  # 30 minutes

substitutions:
  _PROJECT_ID: shanedancy-9f2a3  # Default value, can be overridden
  _REGION: us-central1  # Default value, can be overridden

availableSecrets:
  secretManager:
    - versionName: projects/${_PROJECT_ID}/secrets/service-account-key/versions/latest
      env: 'SERVICE_ACCOUNT_KEY'